Updating code

diff --git a/recovery/root/system/bin/gsirw b/recovery/root/system/bin/gsirw
--- a/recovery/root/system/bin/gsirw
+++ b/recovery/root/system/bin/gsirw
@@ -1,10 +1,12 @@
 #!/system/bin/sh
 
+sudo file -s /dev/block/mmcblk0p38 | grep -o '[A-Z0-9]* filesystem' | awk '{print tolower($1)}'
+
 function generate_date_message() {
   hour=$(echo "$(date +%Hhs:%Mmin)")
   date=$(echo "$(date +%dday/%mmon/%Yyear)")
   date=$(echo "$date" | sed 's/\//|/g')
-  echo "[$hour]($date)"
+  day="$(echo "[$hour]($date)")"
 }
 
 function default() {
@@ -75,7 +77,7 @@ function perform_resize_and_unshare_blocks() {
     echo "Try to fix any Error"
     e2fsck -f "$new_name"
     echo "Unsharing block to get RW Image"
-    e2fsck -E unshare_blocks "$new_name" 2>/dev/null
+    e2fsck -E unshare_blocks "$new_name" 2>$hider
     resize2fs -M "$new_name"
 }
 
@@ -165,11 +167,11 @@ function prank() {
 }
 
 function check_dd() {
-  if ! dd if=/dev/zero of=/dev/Nothing bs=1 count=1 &> /dev/null; then
+  if ! dd if=/dev/zero of=/dev/Nothing bs=1 count=1 &> $hider; then
     echo "The 'dd' command is not available or failed to execute."
   fi
   
-  if dd if=/dev/zero of=/dev/Nothing bs=1 count=1 &> /dev/null; then
+  if dd if=/dev/zero of=/dev/Nothing bs=1 count=1 &> $hider; then
     echo "Congratulations, the 'dd' command is present and can be executed."
   fi
 }
@@ -746,7 +748,7 @@ function perform_ota() {
     echo "Try to fix any Error"
     e2fsck -fp "$image"
     echo "Unsharing block to get RW Image"
-    e2fsck -E unshare_blocks "$image" 2>/dev/null
+    e2fsck -E unshare_blocks "$image" 2>$hider
     resize2fs -M "$image"
 }
 
@@ -758,11 +760,11 @@ function ask() {
 
 function identify_device() {
     if [ -z "$DYNAMIC" ] || [ -z "$GENERIC" ] || [ -z "$DEVICE_MAPPER" ] || [ -z "$A_B" ] || [ -z "$A_O" ]; then
-        if ls /dev/block/mapper >/dev/null 2>&1; then
+        if ls /dev/block/mapper >$hider 2>&1; then
             export DYNAMIC="true"
             export GENERIC="false"
             export DEVICE_MAPPER="/dev/block/mapper"
-        elif ls /dev/block/by-name >/dev/null 2>&1; then
+        elif ls /dev/block/by-name >$hider 2>&1; then
             export DYNAMIC="false"
             export GENERIC="true"
             export DEVICE_MAPPER="/dev/block/by-name"
@@ -791,23 +793,23 @@ function extract_image_from_archive() {
     echo ""
     echo "Extracting $archive..."
     case "$archive" in
-        *.zip) unzip -d "$extracted_dir" "$archive" 2>/dev/null ;;
-        *.tar.gz | *.tgz) tar -xzf "$archive" -C "$extracted_dir" 2>/dev/null ;;
-        *.xz) xz -d "$archive" -c > "$extracted_dir/$(basename "$archive" .xz)" 2>/dev/null ;;
-        *.tar.xz) xz -d "$archive" -c | tar -xf - -C "$extracted_dir" 2>/dev/null ;;
-        *.gz) gunzip -c "$archive" > "$extracted_dir/$(basename "$archive" .gz)" 2>/dev/null ;;
-        *.tar.bz2 | *.tbz2) tar -xjf "$archive" -C "$extracted_dir" 2>/dev/null ;;
-        *.bz2) bunzip2 -c "$archive" > "$extracted_dir/$(basename "$archive" .bz2)" 2>/dev/null ;;
-        *.rar) unrar x "$archive" "$extracted_dir" 2>/dev/null ;;
-        *.7z) 7z x "$archive" -o"$extracted_dir" 2>/dev/null ;;
-        *.lz4) lz4 -d "$archive" "$extracted_dir/$(basename "$archive" .lz4)" 2>/dev/null ;;
-        *.tar.lz4) lz4 -d "$archive" | tar -xf - -C "$extracted_dir" 2>/dev/null ;;
-        *.Z) uncompress -c "$archive" > "$extracted_dir/$(basename "$archive" .Z)" 2>/dev/null ;;
+        *.zip) unzip -d "$extracted_dir" "$archive" 2>$hider ;;
+        *.tar.gz | *.tgz) tar -xzf "$archive" -C "$extracted_dir" 2>$hider ;;
+        *.xz) xz -d "$archive" -c > "$extracted_dir/$(basename "$archive" .xz)" 2>$hider ;;
+        *.tar.xz) xz -d "$archive" -c | tar -xf - -C "$extracted_dir" 2>$hider ;;
+        *.gz) gunzip -c "$archive" > "$extracted_dir/$(basename "$archive" .gz)" 2>$hider ;;
+        *.tar.bz2 | *.tbz2) tar -xjf "$archive" -C "$extracted_dir" 2>$hider ;;
+        *.bz2) bunzip2 -c "$archive" > "$extracted_dir/$(basename "$archive" .bz2)" 2>$hider ;;
+        *.rar) unrar x "$archive" "$extracted_dir" 2>$hider ;;
+        *.7z) 7z x "$archive" -o"$extracted_dir" 2>$hider ;;
+        *.lz4) lz4 -d "$archive" "$extracted_dir/$(basename "$archive" .lz4)" 2>$hider ;;
+        *.tar.lz4) lz4 -d "$archive" | tar -xf - -C "$extracted_dir" 2>$hider ;;
+        *.Z) uncompress -c "$archive" > "$extracted_dir/$(basename "$archive" .Z)" 2>$hider ;;
         *) 
             export extension="${archive##*.}"
-            if command -v "$extension" &> /dev/null; then
-                { "$extension" -d "$archive" -c > "$extracted_dir/$(basename "$archive" ."$extension")" || "$extension" -d "$archive" -C > "$extracted_dir/$(basename "$archive" ."$extension")" || "$extension" -d "$archive" "$extracted_dir/$(basename "$archive" ."$extension")" || "$extension" -c "$archive" > "$extracted_dir/$(basename "$archive" ."$extension")"; } 2>/dev/null
-            elif command -v "extract_$extension" &> /dev/null; then
+            if command -v "$extension" &> $hider; then
+                { "$extension" -d "$archive" -c > "$extracted_dir/$(basename "$archive" ."$extension")" || "$extension" -d "$archive" -C > "$extracted_dir/$(basename "$archive" ."$extension")" || "$extension" -d "$archive" "$extracted_dir/$(basename "$archive" ."$extension")" || "$extension" -c "$archive" > "$extracted_dir/$(basename "$archive" ."$extension")"; } 2>$hider
+            elif command -v "extract_$extension" &> $hider; then
                 "extract_$extension" -d "$archive" -C "$extracted_dir"
             else
                 echo "Unsupported archive format: $archive"; sleep 5; return 1
@@ -853,7 +855,7 @@ function process_image() {
 }
 
 function find_image_in_directory() {
-    export recent_image_file=$(find "$image_path/" -type f -name "*.img" -mmin -17 -exec stat --format='%Y %n' {} + 2>/dev/null | sort -n | tail -n 1 | cut -d' ' -f2-)
+    export recent_image_file=$(find "$image_path/" -type f -name "*.img" -mmin -17 -exec stat --format='%Y %n' {} + 2>$hider | sort -n | tail -n 1 | cut -d' ' -f2-)
     if [ -n "$recent_image_file" ]; then
         found_dir=$(dirname "$recent_image_file")
         found_file=$(basename "$recent_image_file")
@@ -884,19 +886,36 @@ function confirm_flash() {
                 echo
                 if [ "$partition_name" = "." ] || [ "$partition_name" = " " ]; then
                     echo "Invalid partition name. Please enter a valid name."
+                    exit 0
                 fi
             done
-
-            if [ "$A_B" = "true" ]; then
-                dd_image "${device_mapper}${partition_name}_b" "$original_file"
-                dd_image "${device_mapper}${partition_name}_b" "$original_file"
-            elif [ "$A_O" = "true" ]; then
-                dd_image "${device_mapper}${partition_name}" "$original_file"
+            device_mapper=""
+            while [ -z "$device_mapper" ] || [ "$device_mapper" = "." ] || [ "$device_mapper" = " " ]; do
+                echo -n "Enter the device mapper of the partition to flash: "
+                read device_mapper
+                echo
+                if [ "$device_mapper" = "." ] || [ "$device_mapper" = " " ]; then
+                    echo "Invalid device mapper. Please enter a valid name."
+                fi
+            done
+            size_to_flash=$(stat -c %s "$original_file")
+            size_selected=$(stat -c %s "${device_mapper}${partition_name}")
+            if [ "$size_to_flash" -le "$size_selected" ]; then
+                echo "Flashing image $original_file to partition ${device_mapper}${partition_name}"
+                if [ "$A_B" = "true" ]; then
+                    dd_image "${device_mapper}${partition_name}_b" "$original_file"
+                    dd_image "${device_mapper}${partition_name}_b" "$original_file"
+                elif [ "$A_O" = "true" ]; then
+                    dd_image "${device_mapper}${partition_name}" "$original_file"
+                else
+                    echo "Partition type could not be determined."
+                    exit 1
+                fi
+                exit 0
             else
-                echo "Partition type could not be determined."
+                echo "Error: The size of the image file is larger than the selected partition."
                 exit 1
             fi
-            exit 1
             ;;
         n|N)
             exit 1
@@ -936,10 +955,13 @@ function check_extension() {
 }
 
 function mount_dual() {
+    local partition="$1"
+    local mount_point="$2"
+
     if [ -x "/system/bin/toybox" ]; then
         TOYBOX_BIN="/system/bin/toybox"
         echo "Attempting to mount using toybox..."
-        $TOYBOX_BIN mount --bind -t ext4 "$1" "$2" >/dev/null 2>&1
+        $TOYBOX_BIN mount --bind -t $filesystem "$partition" "$mount_point" >$hider 2>&1
         if [ $? -eq 0 ]; then
             echo "Mount successful using toybox"
             success=true
@@ -949,7 +971,7 @@ function mount_dual() {
         fi
     fi
 
-    mount -t ext4 -o rw,noatime "$1" "$2" >/dev/null 2>&1
+    mount -t $filesystem -o rw,noatime "$partition" "$mount_point" >$hider 2>&1
     if [ $? -eq 0 ]; then
         echo "Mount successful using mountutils"
         success=true
@@ -957,8 +979,8 @@ function mount_dual() {
     else
         echo "Mount failed using mountutils as well, trying with losetup..."
         loop_device=$(losetup -f)
-        if losetup "$loop_device" "$1"; then
-            if mount -t ext4 -o rw,noatime "$loop_device" "$2" >/dev/null 2>&1; then
+        if losetup "$loop_device" "$partition"; then
+            if mount -t $filesystem -o rw,noatime "$loop_device" "$mount_point" >$hider 2>&1; then
                 echo "Mount successful using losetup"
                 return 0
             else
@@ -973,11 +995,15 @@ function mount_dual() {
 }
 
 function mount_device() {
+    local partition="$1"
+    local mount_point="$2"
+    local success=false
+    
     loop_device=$(losetup -f)
     success=false
 
-    if losetup "$loop_device" "$1"; then
-        if mount -t ext4 -o rw,noatime "$loop_device" "$2" >/dev/null 2>&1; then
+    if losetup "$loop_device" "$partition"; then
+        if mount -t $filesystem -o rw,noatime "$loop_device" "$mount_point" >$hider 2>&1; then
             success=true
         else
             echo "Error: Mount failed on initial attempt"
@@ -988,29 +1014,29 @@ function mount_device() {
 
     if [ "$success" = false ]; then
         echo "Trying an alternative method"
-        mount_dual "$1" "$2"
+        mount_dual "$partition" "$mount_point"
     fi
 
     if [ "$success" = true ]; then
-        echo "Mounted image on $2 to modify"
+        echo "Mounted image on $mount_point to modify"
         prompt_for_confirmation "Press any key to indicate that you have finished the process... "
-        umount "$2"
+        umount "$mount_point"
         if [ $? -ne 0 ]; then
-            echo "Error: Failed to unmount $2"
+            echo "Error: Failed to unmount $mount_point"
             losetup -d "$loop_device"
             return 1
         fi
 
-        e2fsck -f "$1"
-        resize2fs -M "$1"
+        e2fsck -f "$partition"
+        resize2fs -M "$partition"
         rename_image "$new_name" "$original_file"
         echo "Compressed image and removed mount"
         return 0
     else
         losetup -d "$loop_device"
         echo "Error: No mount command was successful."
-        e2fsck -f "$new_name"
-        resize2fs -M "$new_name"
+        e2fsck -f "$partition"
+        resize2fs -M "$partition"
         echo "Compressed image and failed mount"
         rename_image "$new_name" "$original_file"
         return 1
@@ -1041,12 +1067,12 @@ function list_directories_and_files() {
     local index=1
 
     case "$sort_dir_type" in
-        name_asc) directories=($(ls -d "$directory"/*/ 2>/dev/null | sort));;
-        name_desc) directories=($(ls -d "$directory"/*/ 2>/dev/null | sort -r));;
-        date_asc) directories=($(ls -dt "$directory"/*/ 2>/dev/null));;
-        date_desc) directories=($(ls -dt "$directory"/*/ 2>/dev/null | tac));;
-        size_asc) directories=($(ls -ldS "$directory"/*/ 2>/dev/null | awk '{print $9}'));;
-        size_desc) directories=($(ls -ldSr "$directory"/*/ 2>/dev/null | awk '{print $9}'));;
+        name_asc) directories=($(ls -d "$directory"/*/ 2>$hider | sort));;
+        name_desc) directories=($(ls -d "$directory"/*/ 2>$hider | sort -r));;
+        date_asc) directories=($(ls -dt "$directory"/*/ 2>$hider));;
+        date_desc) directories=($(ls -dt "$directory"/*/ 2>$hider | tac));;
+        size_asc) directories=($(ls -ldS "$directory"/*/ 2>$hider | awk '{print $9}'));;
+        size_desc) directories=($(ls -ldSr "$directory"/*/ 2>$hider | awk '{print $9}'));;
         *) echo "Invalid sort type for directories"; return 1;;
     esac
 
@@ -1255,6 +1281,7 @@ function right_logic() {
         original_file="$image_path/$select_file"
         new_name="$image_path/system.img"
         rename_image "$original_file" "$new_name"
+        filesystem=$(file -sL "$new_name" | grep -o '[A-Z0-9]* filesystem' | awk '{print tolower($1)}')
 
         case "$mode" in
             "user_modification" | "process_user_selected_image")
@@ -1567,15 +1594,15 @@ function MAIN () {
 	NC='\033[0m'
 	
 	export LOGO="$(
-	    echo -n "$(base64 -d <<< "CiBfICAgICBfX18gICAgX19fCiAgL19cICAgfF8gX3wgIC8gXyBcCiAgLyBfIFwgICB8IHwgIHwg==" 2>/dev/null)"
-        echo -n "$(base64 -d <<< "KF8pIHwKL18vIFxfXCB8X19ffCAgXF9fXy8KIF9fX18gX19fXyBfX18gICAgICAgICAgICAgICAg==" 2>/dev/null)"
-        echo -n "$(base64 -d <<< "ICAKIC8gX19fLyBfX198XyBffCAgICAgXyBfX19fICAgICAgX18KfCB8ICBfXF9fXyBcfCB8X19f==" 2>/dev/null)"
-        echo -n "$(base64 -d <<< "X198ICdfX1wgXCAvXCAvIC8KfCB8X3wgfF9fXykgfCB8X19fX198IHwgICBcIFYgIFYgLwpcX19f==" 2>/dev/null)"
-        echo -n "$(base64 -d <<< "X3xfX19fL19fX3wgICAgfF98ICAgIFxfL1xfLwoK==" 2>/dev/null)"
+	    echo -n "$(base64 -d <<< "CiBfICAgICBfX18gICAgX19fCiAgL19cICAgfF8gX3wgIC8gXyBcCiAgLyBfIFwgICB8IHwgIHwg==" 2>$hider)"
+        echo -n "$(base64 -d <<< "KF8pIHwKL18vIFxfXCB8X19ffCAgXF9fXy8KIF9fX18gX19fXyBfX18gICAgICAgICAgICAgICAg==" 2>$hider)"
+        echo -n "$(base64 -d <<< "ICAKIC8gX19fLyBfX198XyBffCAgICAgXyBfX19fICAgICAgX18KfCB8ICBfXF9fXyBcfCB8X19f==" 2>$hider)"
+        echo -n "$(base64 -d <<< "X198ICdfX1wgXCAvXCAvIC8KfCB8X3wgfF9fXykgfCB8X19fX198IHwgICBcIFYgIFYgLwpcX19f==" 2>$hider)"
+        echo -n "$(base64 -d <<< "X3xfX19fL19fX3wgICAgfF98ICAgIFxfL1xfLwoK==" 2>$hider)"
     )"
     
     export LOGOV2="$(
-        export LOGOV2="$(echo -n "$(base64 -d <<< "CiguIFkgLikKKSAgICgKKCAgICAgKQo==" 2>/dev/null)")"
+        export LOGOV2="$(echo -n "$(base64 -d <<< "CiguIFkgLikKKSAgICgKKCAgICAgKQo==" 2>$hider)")"
         center_ansi "$LOGOV2"
     )"
     
@@ -1624,5 +1651,49 @@ function MAIN () {
     esac
 }
 
+function DEBUGER() {
+    check_root_permissions
+    exec_as_root "$@"
+    generate_date_message
+    
+    LOG_FILE="/cache/gsirw-$day.log"
+	DEBUG_LOG="/cache/debug_log_$day.log"
+	
+	if [ "$DEBUG" = "true" ]; then
+		hider="/dev/null"
+    else
+        hider=/dev/null
+    fi
+    
+    if [ "$DEBUG" = "true" ]; then
+      echo "DEBUG Mode Is Enabled"
+      rm -rf /cache/gsirw-*.log
+      rm -rf /cache/debug_log_*.log
+    
+      echo "Script started at $day" >> "$LOG_FILE"
+      echo "Arguments passed: $0" >> "$LOG_FILE"
+    
+      set -x > "$DEBUG_LOG" 2>&1
+    
+      debug_command() {
+        local cmd="$1"
+        echo "Executing command: $cmd" >> "$LOG_FILE"
+        eval "$cmd" 2>&1 | tee -a "$LOG_FILE"
+        echo "Command finished: $cmd" >> "$LOG_FILE"
+      }
 
-MAIN "$@"
+      debug_command "MAIN $@"
+    
+      set +x > /dev/tty 2>&1
+      cat "$DEBUG_LOG" >> "$LOG_FILE"
+      rm "$DEBUG_LOG"
+    
+      echo "Script finished at $(date)" >> "$LOG_FILE"
+    else
+      MAIN "$@"
+    fi
+}
+
+DEBUG=true
+
+DEBUGER "$@"
